const functionalitiesToAdd = [
  {
    name: 'Apšvietimo jungimas',
    group: 'Apšvietimas',
    longDescription: 'tai procesas, kai elektrinė įranga arba prietaisai yra įjungiami arba išjungiami. Šis procesas gali būti atliekamas rankiniu būdu, naudojant mechaninius arba elektroninius įrenginius, arba automatiškai, pagal tam tikrus nustatytus sąlygų ar veikimo principų. ',
    shortDescription: '',
  },
  {
    name: 'Apšvietimo šviesumo reguliavimas',
    group: 'Apšvietimas',
    longDescription: 'tai  procesas, kai reguliuojama šviesos šaltinio išspinduliavimo galia, kad būtų pasiektas norimas šviesos lygis. Tai gali būti atliekama naudojant specialius įtaisus arba technologijas, kurios keičia elektros srovės įtampą arba dažnį, taip mažindamos ar didindamos šviesos stiprumą.',
    shortDescription: '',
  },
  {
    name: 'Spalvos temperatūra',
    group: 'Apšvietimas',
    longDescription: 'tai yra matavimas, skirtas apibūdinti šviesos spalvą, kuri yra išreikšta Kelvinų (K) skalėje. Ji apibūdina šviesos šaltinio spektrinį sudėjimą ir yra susijusi su spalvos tonu, kuriame šviesos šaltinis spinduliuoja.',
    shortDescription: '',
  },
  {
    name: 'Spalva',
    group: 'Apšvietimas',
    longDescription: 'tai yra svarbi funkcija šviesos apšvietime, nes ji nulemia objekto arba scenos vizualinį įspūdį. Šviesos spalva priklauso nuo šviesos šaltinio spektrinio turinio ir apšvietimo aplinkos.',
    shortDescription: '',
  },
  {
    name: 'Sekos',
    group: 'Apšvietimas',
    longDescription: '- sviesos apšvietime gali būti suprantama kaip iš anksto nustatytas šviesos šaltinio veiksmų arba šviesos šviesos efektų serijos. Tai gali apimti šviesos šaltinio įjungimą arba išjungimą tam tikru laiku, spalvų perėjimą, šviesos stiprumo pokyčius, judančius šviesos efektus ir kitus šviesos pokyčius. ',
    shortDescription: '',
  },
  {
    name: 'Užuolaidos',
    group: 'Langų ir durų valdymas',
    longDescription: 'šviesos apšvietime gali būti naudojamos kaip funkcija, leidžianti kontroliuoti šviesos kryptį arba intensyvumą. Šviesos žaliuzės arba lankstūs šviesos elementai gali būti reguliuojami, kad būtų pasiekta norima šviesos skleidimo kryptis arba plotas.',
    shortDescription: '',
  },
  {
    name: 'Žaliuzės',
    group: 'Langų ir durų valdymas',
    longDescription: 'šviesos apšvietime gali būti naudojamos kaip funkcija, leidžianti reguliuoti šviesos srautą arba intensyvumą. Šviesos skliautai yra reguliuojami lanksčios konstrukcijos elementai, kurie gali būti atidaromi arba uždaromi, siekiant kontroliuoti šviesos kiekį, kuris patenka į tam tikrą erdvę arba objektą.',
    shortDescription: '',
  },
  {
    name: 'Markizės',
    group: 'Langų ir durų valdymas',
    longDescription: 'tai  yra apsauginiai ir dekoratyviniai elementai, kurie dedami virš langų, durų ar terasų, siekiant apsaugoti nuo tiesioginių saulės spindulių arba lietaus.',
    shortDescription: '',
  },
  {
    name: 'Stoglangiai',
    group: 'Langų ir durų valdymas',
    longDescription: 'tai yra specialios lango formos konstrukcijos, kurios įmontuojamos į stogą ir leidžia natūraliam šviesos srautui patenkinti į patalpas iš viršaus. Šios šviesos elementai gali būti statomos iš stiklo arba plastiko ir paprastai yra dizainuotos taip, kad būtų atsparios vandeniui.',
    shortDescription: '',
  },
  {
    name: 'Langai su grotomis',
    group: 'Langų ir durų valdymas',
    longDescription: 'Funkcija, skirta valdyti langus su grotomis.',
    shortDescription: '',
  },
  {
    name: 'Vėdinimo sklendės',
    group: 'Langų ir durų valdymas',
    longDescription: 'tai yra elementai, kurie leidžia reguliuoti oro srautą tarp vidaus ir išorės.',
    shortDescription: '',
  },
  {
    name: 'Apsauga',
    group: 'Apsauga',
    longDescription: 'smart namų sistemoje yra svarbi funkcija, skirta užtikrinti gyventojų ir jų turtų apsaugą. Ši funkcija apima įvairius įrankius ir technologijas, kurios leidžia atpažinti ir reaguoti į bet kokius potencialius pavojus ar nesklandumus. ',
    shortDescription: '',
  },
  {
    name: 'Audrų/lietaus stebėjimo sistema (palydovinis įrenga)',
    group: 'Apsauga',
    longDescription: 'gali būti vertinama kaip speciali prietaiso dalis, kuri yra integruota į smart home sistemą ir skirta stebėti oro sąlygas, ypač susijusias su audromis ir lietumi. Ši prietaiso dalis gali būti susijusi su meteorologinėmis stebėsenos sistemomis arba gauti informaciją iš meteorologinių palydovų.',
    shortDescription: '',
  },
  {
    name: 'Audrų/lietaus stebėjimo sistema (universalus siųstuvas)',
    group: 'Apsauga',
    longDescription: 'gali būti vertinama kaip įrenginys, skirtas detaliai stebėti oro sąlygas, ypač susijusias su audromis ir lietumi, ir siųsti šią informaciją į smart home sistemą. Šis universalus perdaviklis gali būti susijęs su įvairiomis meteorologinėmis stebėsenos sistemomis arba palydovinėmis tarnybomis, kurios teikia informaciją apie orus.',
    shortDescription: '',
  },
  {
    name: 'Nuotėkis',
    group: 'Apsauga',
    longDescription: 'smart home sistemoje gali būti vertinama kaip funkcija, skirta aptikti vandens nutekėjimus arba nuotėkį namų viduje ir nedelsiant pranešti apie tai gyventojams. Ši funkcija gali būti įgyvendinta naudojant specialius vandens jutiklius arba sensorius, kurie yra įdiegti tam tikruose strategiškai svarbiuose vietose, tokiuose kaip virtuvės, vonios kambariai, skalbimo mašinos arba kiti vandens naudojimo taškai.',
    shortDescription: '',
  },
  {
    name: 'Kondensatas',
    group: 'Apsauga',
    longDescription: 'smart home sistemoje gali būti suprantama kaip funkcija, skirta aptikti kondensacijos atsiradimą ir valdyti tai susijusius veiksmus. Kondensacija yra procesas, kai oro drėgmė prisikerta ant šalto paviršiaus, pavyzdžiui, langų ar veidrodžių, ir virsta vandens lašais arba rūkeliu. Šis reiškinys gali sukelti ne tik estetinę problemą, bet ir potencialią pavojų namo interjero kokybei ir struktūros pažeidimą.',
    shortDescription: '',
  },
  {
    name: 'CO2',
    group: 'Apsauga',
    longDescription: 'smart home sistemoje gali būti suprantama kaip funkcija, skirta aptikti anglies dioksido lygį patalpose ir įvairiais būdais valdyti oro kokybę.',
    shortDescription: '',
  },
  {
    name: 'Radiatorių termostatas',
    group: 'Šildymas/ventiliacija/oro kondicionavimas',
    longDescription: 'smart home sistemoje yra funkcija, kuri leidžia valdyti šildymo sistemos radiatorius naudojant išmaniuosius termostatus. Šis termostatas yra įdiegtas ant radiatoriaus ir gali būti valdomas išmaniajame telefone arba kitaip integruotoje sistemoje.Pagrindinė radiatoriaus termostato funkcija yra reguliuoti kambario temperatūrą, valdydama radiatoriaus šilumos išmetimą. Tai leidžia gyventojams individualiai nustatyti kiekvieno kambario temperatūrą ir taupyti energiją, nes galima nustatyti optimalų šilumos lygį kiekvienam kambaryje atsižvelgiant į jo naudojimąsi ir asmeninius poreikius.',
    shortDescription: '',
  },
  {
    name: 'Sieninis termostatas',
    group: 'Šildymas/ventiliacija/oro kondicionavimas',
    longDescription: 'tai yra įrenginys, kuris montuojamas ant sienos ir naudojamas valdyti kambario temperatūrą. Tai gali būti svarbi funkcija smart home sistemoje.Pagrindinė sieninio termostato funkcija yra reguliuoti šildymo arba vėdinimo sistemą, kad būtų išlaikytas pageidaujamas kambario temperatūros lygis. Įrenginys gali būti valdomas rankiniu būdu, naudojant jo fizinį ekraną ir mygtukus, arba automatiškai, pagal nustatytus grafikus arba scenarijus.',
    shortDescription: '',
  },
  {
    name: 'Boileris',
    group: 'Šildymas/ventiliacija/oro kondicionavimas',
    longDescription: 'tai yra svarbus prietaisas šildymo sistemoje, kuris naudojamas šildyti vandenį. Tai svarbi funkcija smart home sistemoje, nes leidžia valdyti šildymo sistemą ir vandens šildymą, kad būtų optimizuotas energijos naudojimas ir patogumas.',
    shortDescription: '',
  },
  {
    name: 'Grindų šildymas',
    group: 'Šildymas/ventiliacija/oro kondicionavimas',
    longDescription: 'tai yra šildymo sistema, kurioje šiluma yra paskirstoma per grindis, o ne per tradicinius radiatorius ar oro srautus. Tai svarbi funkcija smart home sistemoje, nes leidžia valdyti kambario temperatūrą efektyviai ir komfortiškai.',
    shortDescription: '',
  },
  {
    name: 'Ventiliacija',
    group: 'Šildymas/ventiliacija/oro kondicionavimas',
    longDescription: 'tai yra svarbi funkcija smart home sistemoje, skirta valdyti oro cirkuliaciją ir kokybę patalpose.',
    shortDescription: '',
  },
  {
    name: 'Scenos per sieninį perdavėją ',
    group: 'Scenos',
    longDescription: 'tai reiškia, kad per sieninį perdavėją (pultelį) galima valdyti skirtingus scenarijus arba nustatymus smart home sistemoje. Scenos gali apimti įvairius veiksmus, pvz., reguliuoti apšvietimą, temperatūrą, uždaryti ar atidaryti žaliuzes ir kt. Sieninis perdavėjas suteikia patogumą ir greitą prieigą prie įvairių namo funkcijų, leisdamas greitai prisitaikyti prie gyvenimo būdo ar pageidavimų.',
    shortDescription: '',
  },
  {
    name: 'Scenos per programėlę',
    group: 'Scenos',
    longDescription: 'tai reiškia, kad per mobiliąją aplikaciją galima valdyti skirtingus scenarijus arba nustatymus smart home sistemoje. Scenos gali apimti įvairius veiksmus, pvz., įjungti ar išjungti apšvietimą, reguliuoti temperatūrą, valdyti saugumo sistemas ir kt. Mobili aplikacija suteikia patogumą ir galimybę valdyti namo funkcijas iš bet kurios vietos, kur yra interneto ryšys.',
    shortDescription: '',
  },
  {
    name: 'Scenos per balsų valdymą ',
    group: 'Scenos',
    longDescription: 'tai reiškia, kad galima valdyti skirtingus scenarijus ar nustatymus smart home sistemoje naudojant balso komandas arba balsų asistentus, tokius kaip "Alexa" ar "Google Assistant". Ši funkcija leidžia vartotojams aktyvuoti norimus scenarijus ar nustatymus, tiesiog kalbant į įrenginį, kuris turi integruotą balso valdymo technologiją.',
    shortDescription: '',
  },
  {
    name: 'Iki 34 scenų',
    group: 'Scenos',
    longDescription: '- tai reiškia, kad yra galimybė sukurti arba programuoti iki 34 skirtingus scenarijus arba nustatymus smart home sistemoje. Šios scenos gali apimti įvairius veiksmus, tokius kaip įjungti/arba išjungti apšvietimą, reguliuoti temperatūrą, valdyti saugumo sistemas ir pan. Tai suteikia vartotojams didelį lankstumą ir galimybes pritaikyti savo namų automatizavimą pagal asmeninius poreikius ir gyvenimo būdą.',
    shortDescription: '',
  },
  {
    name: 'Daugiau nei 100 scenų',
    group: 'Scenos',
    longDescription: 'tai reiškia, kad yra galimybė sukurti arba programuoti daugiau nei 100 skirtingų scenarijų ar nustatymų smart home sistemoje. Šios scenos gali apimti įvairius veiksmus, pavyzdžiui, įjungti ar išjungti apšvietimą, reguliuoti temperatūrą, valdyti saugumo sistemas ir t.t. Tai suteikia vartotojams labai didelį lankstumą ir galimybes pritaikyti savo namų automatizavimą pagal asmeninius poreikius ir gyvenimo būdą.',
    shortDescription: '',
  },
  {
    name: 'Neribotas scenų kiekis',
    group: 'Scenos',
    longDescription: 'tai reiškia, kad nėra jokio apribojimo, kiek scenų galima sukurti arba programuoti smart namų sistemoje. Vartotojai gali kurti tiek scenų, kiek nori, ir pritaikyti jas pagal savo individualius poreikius bei gyvenimo būdą. Tai suteikia didelį lankstumą ir galimybes maksimaliai pritaikyti automatizavimą pagal jų norus ir aplinkybes.',
    shortDescription: '',
  },
  {
    name: 'Energijos matavimas',
    group: 'Energija',
    longDescription: 'tai yra funkcija, kuri leidžia matuoti, stebėti ir įvertinti elektros energijos naudojimą namuose arba įrenginyje. Ši funkcija gali būti integruota į smart home sistemą ir suteikti vartotojui informaciją apie tai, kiek energijos naudojama, kada ji naudojama ir kaip ji gali būti efektyviau valdoma. Tai padeda vartotojams sekti jų energijos sąnaudas, identifikuoti taupymo galimybes ir padėti priimti informuotus sprendimus, siekiant sumažinti energijos sąnaudas ir išlaikyti efektyvų energijos naudojimą.',
    shortDescription: '',
  },
  {
    name: 'SENEC namų baterijos saugojimas',
    group: 'Energija',
    longDescription: 'tai yra sistema, kuri leidžia saugoti perteklinę elektros energiją, pagamintą iš saulės ar kitų energijos šaltinių, naudojant baterijas. Ši sistema leidžia vartotojams naudoti saugotą energiją, kai jos reikia, pavyzdžiui, vakare ar rūsyje, kai saulė nenusileidžia arba elektros energijos poreikis yra didesnis. Tai padeda sumažinti elektros sąnaudas ir padidina savarankiškumą, naudojant alternatyvius energijos šaltinius.',
    shortDescription: '',
  },
  {
    name: 'Oro prognozė',
    group: 'Oras',
    longDescription: 'tai yra informacija, kuri teikia numatytą orų būklę tam tikrame regione ateinančiomis dienomis ar valandomis. Ši informacija gali apimti temperatūrą, drėgmę, vėjo greitį ir kryptį, kritulių tikimybę ir kitus oro sąlygų rodiklius. Oro prognozės yra svarbios planuojant veiklą lauke arba pasiruošiant tam tikriems orų sąlygoms. Daugelis smart home sistemų gali įtraukti oro prognozės funkciją, kad vartotojams būtų lengviau planuoti jų dienas ir reguliuoti namų komfortą pagal numatytas orų sąlygas.',
    shortDescription: '',
  },
  {
    name: 'Oro stotelė',
    group: 'Oras',
    longDescription: 'tai yra įrenginys, skirtas matuoti ir stebėti įvairius orų parametrus, tokiais kaip temperatūra, drėgmė, vėjo greitis ir kryptis, kritulių kiekis, slėgis ir kt. Oro stotelės gali būti naudojamos tiek asmeniniams, tiek komerciniams tikslams, teikianti išsamesnę ir tikslią informaciją apie orų sąlygas tam tikrame regione. Šios stotelės gali būti įdiegtos namų aplinkoje arba įvairiose vietose, pavyzdžiui, miestų centrų stoguose, oro uostuose, laivybose ar netgi kosminėse misijose. Taip pat įvairios smart home sistemos gali naudoti duomenis iš oro stotelės, kad būtų suteikta išsamesnė ir asmeniškesnė informacija apie orų sąlygas ir pagal tai prisitaikyti automatizuoti namų funkcijas.',
    shortDescription: '',
  },
  {
    name: 'Taisyklių kūrimas audrų atveju',
    group: 'Oras',
    longDescription: 'tai reiškia sukurti nustatytas instrukcijas ar veiksmus, kurie bus vykdomi, kai įvyksta audros ar stiprūs atmosferos sąlygų pokyčiai.',
    shortDescription: '',
  },
  {
    name: 'Langų ir durų stebėjimas',
    group: 'Saugumas',
    longDescription: 'Funkcija, leidžianti stebėti langų ir durų būklę.',
    shortDescription: '',
  },
  {
    name: 'Langų jutikliai',
    group: 'Saugumas',
    longDescription: 'tai yra įrenginiai, kurie yra sumontuoti ant langų ar durų ir skirti aptikti jų atidarymą ar uždarymą. Šie jutikliai gali būti dalis saugumo sistemos ir leidžia vartotojams stebėti ir valdyti namų saugumą. Kai langai ar durys yra atidaromi, jutikliai gali išsiųsti signalą į centrinę kontrolės sistemą, kuri gali inicijuoti įvairius veiksmus, pavyzdžiui, įjungti apsaugos signalą arba pranešti vartotojams apie galimą pavojų. Tai padeda užtikrinti namų saugumą ir apsaugą nuo nepageidaujamų įsilaužimų arba nelaimingų atsitikimų.',
    shortDescription: '',
  },
  {
    name: 'Durų jutikliai',
    group: 'Saugumas',
    longDescription: 'tai  yra įrenginiai, kurie montuojami ant durų ir skirti aptikti jų atidarymą ar uždarymą. Šie jutikliai yra svarbus komponentas saugumo sistemose ir leidžia vartotojams stebėti ir kontroliuoti durų būseną.Kai durys yra atidarytos ar uždarytos, jutikliai gali nustatyti šią būseną ir siųsti signalą į centralinę valdymo sistemą. Tai leidžia sistemos vartotojams gauti pranešimus apie durų būseną ir atlikti tam tikrus veiksmus, pavyzdžiui, įjungti arba išjungti saugumo funkcijas, registruoti durų naudojimo laiką arba prireikus pranešti apie nepageidaujamus įvykius, tokius kaip įsilaužimai.',
    shortDescription: '',
  },
  {
    name: 'Spynos jungiklių kontaktai',
    group: 'Saugumas',
    longDescription: 'tai yra kontaktai, kurie yra susiję su mirtinės spynos mechanizmu. Mirtinoji spyna yra mechanizmas, kuris yra sumontuotas ant durų ir suteikia papildomą saugumą užrakindamas duris iš vidaus. Kai spyna yra įsijungiama arba išjungiama, šie kontaktai aptinka šią būseną ir gali siųsti signalą į centrinius valdymo sistemą.',
    shortDescription: '',
  },
  {
    name: 'Reikšmių rodymas',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo įvairias reikšmes.',
    shortDescription: '',
  },
  {
    name: 'Apšvietimo intensyvumas (lux)',
    group: 'Informacija',
    longDescription: 'tai yra vienetas, skirtas matuoti apšvietimo lygį arba šviesos intensyvumą. Tai reiškia, kiek šviesos yra apšviečiama tam tikroje vietoje arba plotelyje',
    shortDescription: '',
  },
  {
    name: 'Temperatūra (°C)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo temperatūrą laipsniais Celsijaus.',
    shortDescription: '',
  },
  {
    name: 'Galia (W)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo galios suvartojimą vatų.',
    shortDescription: '',
  },
  {
    name: 'Energijos suvartojimas (kWh)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo energijos suvartojimą kilovatvalandėmis.',
    shortDescription: '',
  },
  {
    name: 'Drėgmė (g/m³)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo drėgmę gramais kubiniame metrų.',
    shortDescription: '',
  },
  {
    name: 'CO² koncentracija (ppm)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo anglies dioksido koncentraciją ppm (dalių per milijoną).',
    shortDescription: '',
  },
  {
    name: 'Autonomija (%)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo autonomijos lygį procentais.',
    shortDescription: '',
  },
  {
    name: 'Darbo valandos (h)',
    group: 'Informacija',
    longDescription: 'Funkcija, kuri rodo įrenginio darbo valandas.',
    shortDescription: '',
  },
  {
    name: 'Laikmačiai su laiko juosta (įskaitant Astro funkciją)',
    group: 'Valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti laikmačius su laiko juosta ir įtraukti Astro funkciją.',
    shortDescription: '',
  },
  {
    name: '40 laikmačių nustatymo kartai',
    group: 'Valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 40 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Astro funkcija',
    group: 'Valdymas',
    longDescription: 'Funkcija, kuri leidžia naudoti astronominius laiko nustatymus.',
    shortDescription: '',
  },
  {
    name: 'Iki 100 laikmačių nustatymo kartai',
    group: 'Valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 100 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Iki 250 laikmačių nustatymo kartai',
    group: 'Valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 250 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Iki 256 laikmačių nustatymo kartai',
    group: 'Valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 256 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Vartotojo galimybės konfigūruoti',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti vartotojui konfigūruoti įvairius nustatymus.',
    shortDescription: '',
  },
  {
    name: 'Laikmatis',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti laiko programas.',
    shortDescription: '',
  },
  {
    name: 'Įjungimo ryškumas',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti įjungimo ryškumą.',
    shortDescription: '',
  },
  {
    name: 'Minimalus/maksimalus ryškumas',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti minimalų/maksimalų ryškumą.',
    shortDescription: '',
  },
  {
    name: 'Įjungimo/išjungimo uždelsimas',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti įjungimo/išjungimo uždelsimą.',
    shortDescription: '',
  },
  {
    name: 'Judesio jutiklio aptikimo sritys',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti judesio jutiklio aptikimo group.',
    shortDescription: '',
  },
  {
    name: 'Naktinis apšvietimas',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti naktinio apšvietimo funkciją.',
    shortDescription: '',
  },
  {
    name: 'Viešbučio funkcija',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti viešbučio funkciją.',
    shortDescription: '',
  },
  {
    name: 'Mėgstamiausi',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti mėgstamiausius nustatymus.',
    shortDescription: '',
  },
  {
    name: 'Scenos',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti scenas.',
    shortDescription: '',
  },
  {
    name: 'Taisyklės',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti taisykles.',
    shortDescription: '',
  },
  {
    name: 'Laikmatis',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti laiko programas.',
    shortDescription: '',
  },
  {
    name: 'Balso paslauga',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti balso paslaugą.',
    shortDescription: '',
  },
  {
    name: 'Nuotolinis prieiga',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti nuotolinę prieigą.',
    shortDescription: '',
  },
  {
    name: 'tado° šildymo sprendimas',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti valdyti tado° šildymo sprendimą.',
    shortDescription: '',
  },
  {
    name: 'Mėgstamiausi',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti mėgstamiausius nustatymus.',
    shortDescription: '',
  },
  {
    name: 'Scenos',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti scenas.',
    shortDescription: '',
  },
  {
    name: 'Taisyklės (veiksmai)',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti taisyklių veiksmus.',
    shortDescription: '',
  },
  {
    name: 'Laikmatis',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti laiko programas.',
    shortDescription: '',
  },
  {
    name: 'Balso paslauga',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti balso paslaugą.',
    shortDescription: '',
  },
  {
    name: 'Nuotolinis prieiga',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti nuotolinę prieigą.',
    shortDescription: '',
  },
  {
    name: 'Philips Hue',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti valdyti Philips Hue įrangą.',
    shortDescription: '',
  },
  {
    name: 'Sonos',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti valdyti Sonos įrangą.',
    shortDescription: '',
  },
  {
    name: 'Scenos',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti scenas.',
    shortDescription: '',
  },
  {
    name: 'Taisyklės',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti taisykles.',
    shortDescription: '',
  },
  {
    name: 'Laikmatis',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti nustatyti laiko programas.',
    shortDescription: '',
  },
  {
    name: 'Balso paslauga',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti balso paslaugą.',
    shortDescription: '',
  },
  {
    name: 'Nuotolinis prieiga',
    group: 'Konfigūracija',
    longDescription: 'Funkcija, leidžianti naudoti nuotolinę prieigą.',
    shortDescription: '',
  },
  {
    name: 'Vartotojo valdymas',
    group: 'Vartotojų valdymas',
    longDescription: 'Funkcija, leidžianti valdyti vartotojus ir jų leidimus sistemoje.',
    shortDescription: '',
  },
  {
    name: 'Vartotojas',
    group: 'Vartotojų valdymas',
    longDescription: 'Vartotojas su standartiniais leidimais.',
    shortDescription: '',
  },
  {
    name: 'Slaptažodis',
    group: 'Vartotojų valdymas',
    longDescription: 'Funkcija, leidžianti nustatyti slaptažodį vartotojo paskyrai.',
    shortDescription: '',
  },
  {
    name: 'Administratorius',
    group: 'Vartotojų valdymas',
    longDescription: 'Vartotojas su visais valdymo leidimais sistemoje.',
    shortDescription: '',
  },
  {
    name: 'Vartotojas su keitimo leidimais',
    group: 'Vartotojų valdymas',
    longDescription: 'Vartotojas, kuriam leidžiama keisti tam tikrus nustatymus.',
    shortDescription: '',
  },
  {
    name: 'Vartotojas be keitimo leidimų',
    group: 'Vartotojų valdymas',
    longDescription: 'Vartotojas, kuriam neleidžiama keisti nustatymų.',
    shortDescription: '',
  },
  {
    name: 'Administratorius su laisvai nustatomais leidimais',
    group: 'Vartotojų valdymas',
    longDescription: 'Administratorius su galimybe laisvai nustatyti vartotojų leidimus.',
    shortDescription: '',
  },
  {
    name: 'Iki 24 vartotojai su laisvai nustatomais leidimais',
    group: 'Vartotojų valdymas',
    longDescription: 'Sistema, leidžianti sukurti iki 24 vartotojus su laisvai nustatomais leidimais.',
    shortDescription: '',
  },
  {
    name: 'Administratorius su laisvai nustatomais leidimais',
    group: 'Vartotojų valdymas',
    longDescription: 'Administratorius su galimybe laisvai nustatyti vartotojų leidimus.',
    shortDescription: '',
  },
  {
    name: 'Iki 150 vartotojų su laisvai nustatomais leidimais',
    group: 'Vartotojų valdymas',
    longDescription: 'Sistema, leidžianti sukurti iki 150 vartotojų su laisvai nustatomais leidimais.',
    shortDescription: '',
  },
  {
    name: 'Buvimo simuliacija',
    group: 'Saugumo sistemos',
    longDescription: 'Funkcija, kuri naudoja įrenginio atmintį ir laiko programavimą, norint sukurti buvimo simuliaciją. Galima sukurti simuliaciją, kuri tęsis 24 valandas, ir kuri naudos laiko programavimo funkciją. Taip pat galima sukurti specifiškai sukurtą simuliaciją, įtraukiant atsitiktinę funkciją.',
    shortDescription: '',
  },
  {
    name: 'Atsitiktinė buvimo simuliacija',
    group: 'Saugumo sistemos',
    longDescription: 'Buvimo simuliacija, kurioje naudojamas atsitiktinės funkcijos elementas, kuris suteikia įspūdį, kad namuose yra žmonių, net kai jie nėra.',
    shortDescription: '',
  },
  {
    name: 'Logikos funkcijos (jeigu-tada)',
    group: 'Logikos funkcijos',
    longDescription: 'Ši funkcija leidžia nustatyti iki 32 jeigu-tada sąlygas su galimybe naudoti operatorius AND, OR ir XOR. Taip pat galima sukurti iki 250 jeigu-tada sąlygas su operatoriais AND, OR ir XOR. Šios funkcijos taip pat leidžia naudoti papildomas funkcijas, tokiu kaip skaitiklis, asmeniniai scenarijai ir neribojama jeigu-tada sąlygų kiekis.',
    shortDescription: '',
  },
  {
    name: 'Logikos funkcijos (jeigu-tada)',
    group: 'Logikos funkcijos',
    longDescription: 'Ši funkcija leidžia nustatyti iki 32 jeigu-tada sąlygas su galimybe naudoti operatorius AND, OR ir XOR. Taip pat galima sukurti iki 250 jeigu-tada sąlygas su operatoriais AND, OR ir XOR. Šios funkcijos taip pat leidžia naudoti papildomas funkcijas, tokiu kaip skaitiklis, asmeniniai scenarijai ir neribojama jeigu-tada sąlygų kiekis.',
    shortDescription: '',
  },
  {
    name: 'Automatinis apšvietimo valdymas',
    group: 'apšvietimas',
    value: 'automatinis-apsvietimo-valdymas',
    longDescription: 'Ši funkcija leidžia automatizuoti namų apšvietimą, taikant įvairius scenarijus ir valdymo būdus. Ji leidžia nustatyti apšvietimo lygį priklausomai nuo dienos laiko, judesio ar kitų parametrų. Tai ne tik padeda sutaupyti energiją, bet ir užtikrina patogumą ir saugumą.',
    shortDescription: '',
  },
  {
    name: 'Garso sistema',
    group: 'bendra',
    value: 'garso-sistema',
    longDescription: 'Garso sistema yra funkcija, kuri leidžia vartotojams valdyti garsą įvairiuose namo zonuose. Tai apima galimybę valdyti garsiakalbius, ausines ar net integraciją su "smart" televizoriais. Garso sistemos funkcionalumas gali būti integruotas su kitomis namų automatizavimo sistemomis, suteikiant plačias galimybes namų pramogų ir patogumo srityse.',
    shortDescription: '',
  },
  {
    name: 'Vartotojo buvimo sekimas',
    group: 'saugos-sistemos',
    value: 'vartotojo-buvimo-sekimas',
    longDescription: 'Vartotojo buvimo sekimas yra funkcija, kuri naudoja judesio jutiklius nustatyti, kada žmonės yra namuose arba išvykę. Tai leidžia stebėti ir valdyti namo saugumą bei efektyviai naudoti energiją, nustatant įspėjimus arba automatizuotus veiksmus priklausomai nuo vartotojų buvimo.',
    shortDescription: '',
  },
  {
    name: 'Klimato valdymas, inžinerinės sistemos',
    group: 'klimato-valdymas-inzinerines-sistemos',
    value: 'klimato-valdymas-inzinerines-sistemos',
    longDescription: 'Ši funkcija leidžia valdyti klimato parametrus namuose, įskaitant temperatūrą, drėgmę ir oro srautus. Ji taip pat integruojama su inžinerinėmis sistemomis, tokiomis kaip šildymas, vėdinimas ir oro kondicionavimas, siekiant užtikrinti optimalią aplinką vartotojams.',
    shortDescription: '',
  },
  {
    name: 'Apšvietimas išmaniuosiuose namuose',
    group: 'apsvietimas-ismaniuosiuose-namuose',
    value: 'apsvietimas-ismaniuosiuose-namuose',
    longDescription: 'Ši funkcija leidžia valdyti apšvietimo sistemos veikimą išmaniuose namuose naudojant įvairias technologijas, tokias kaip LED šviesos šaltiniai ir išmanieji jungikliai. Tai ne tik suteikia vartotojams galimybę reguliuoti apšvietimo lygį ir atmosferą, bet ir padeda taupyti energiją.',
    shortDescription: '',
  },
  {
    name: 'Langų ir žaliuzių valdymas',
    group: 'langu-ir-zaliuziu-valdymas',
    value: 'langu-ir-zaliuziu-valdymas',
    longDescription: 'Ši funkcija leidžia valdyti langų ir žaliuzių veikimą išmaniuose namuose, naudojant automatizavimo technologijas. Tai apima galimybę atidaryti, uždaryti ar net reguliuoti langų atspalvį ir skaidrumą, taip pat valdyti žaliuzes priklausomai nuo dienos laiko ar išorės sąlygų.',
    shortDescription: '',
  },
  {
    name: 'Saugos sistemos',
    group: 'saugos-sistemos',
    value: 'saugos-sistemos',
    longDescription: 'Ši funkcija apima visus saugos sistemų komponentus ir funkcionalumus, skirtus apsaugoti namą ir gyventojus nuo įvairių pavojų, įskaitant vagystes, gaisrus ir nelaimingus atsitikimus. Tai apima judesio jutiklius, vaizdo stebėjimo kameras, dujų ir dūmų detektorius bei kitus saugos prietaisus.',
    shortDescription: '',
  },
  {
    name: 'Komforto įranga',
    group: 'komforto-iranga',
    value: 'komforto-iranga',
    longDescription: 'Ši funkcija apima įvairius įrangos sprendimus, kurie padeda padidinti vartotojų komfortą ir patogumą namuose. Tai gali būti susiję su ergonomiškomis baldų išdėstymo schemomis, specializuotomis patogumo funkcijomis ar net automatizuotomis kasdieninėmis veiklomis.',
   shortDescription: 'Funkcija skirta didinti komfortą ir patogumą namuose.',
  },
  {
    name: 'Energijos šaltiniai',
    group: 'energijos-saltiniai',
    value: 'energijos-saltiniai',
    longDescription: 'Ši funkcija apima skirtingus energijos tiekimo šaltinius, kurie gali būti naudojami namuose, įskaitant elektrą, dujas, saulės energiją ir kt. Tai leidžia vartotojams pasirinkti efektyviausią ir tvariausią energijos šaltinį, atsižvelgiant į jų poreikius ir aplinkosaugos aspektus.',
    shortDescription: 'Funkcija skirta energijos tiekimo šaltinių valdymui namuose.',
  },
  {
  name: 'Apšvietimo jungiklis',
  group: 'apšvietimas',
  value: 'apsvietimo-jungiklis',
  longDescription: 'Funkcija, skirta valdyti apšvietimą - įjungti/išjungti.',
  shortDescription: '',
  },
  {
  name: 'Apšvietimo reguliavimas',
  group: 'apšvietimas',
  value: 'apsvietimo-reguliavimas',
  longDescription: 'Funkcija, leidžianti reguliuoti apšvietimo intensyvumą.',
  shortDescription: '',
  },
  {
  name: 'Šviesos temperatūros reguliavimas',
  group: 'apšvietimas',
  value: 'sviesos-temperaturos-reguliavimas',
  longDescription: 'Funkcija, leidžianti reguliuoti šviesos spalvą ar temperatūrą.',
  shortDescription: '',
  },
  {
  name: 'Spalvos reguliavimas',
  group: 'apšvietimas',
  value: 'spalvos-reguliavimas',
  longDescription: 'Funkcija, skirta valdyti apšvietimo spalvą.',
  shortDescription: '',
  },
  {
  name: 'Sekos',
  group: 'apšvietimas',
  value: 'sekos',
  longDescription: 'Funkcija, skirta kurti sekas apšvietimui.',
  shortDescription: '',
  },
  {
  name: 'Žaliuzės',
  group: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'zaliuzes',
  longDescription: 'Funkcija, skirta valdyti žaliuzes.',
  shortDescription: '',
  },
  {
  name: 'Šutteriai',
  group: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'sutteriai',
  longDescription: 'Funkcija, skirta valdyti šutterius.',
  shortDescription: '',
  },
  {
  name: 'Markizės',
  group: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'markizes',
  longDescription: 'Funkcija, skirta valdyti markizes.',
  shortDescription: '',
  },
  {
  name: 'Ventiliacijos sklendės',
  group: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'ventiliacijos-sklendes',
  longDescription: 'Funkcija, skirta valdyti ventiliacijos sklendes.',
  shortDescription: '',
  },
  {
  name: 'Langų stogai',
  group: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'langus-stogai',
  longDescription: 'Funkcija, skirta valdyti langų stogus.',
  shortDescription: '',
  },
  {
  name: 'Saugumo šešėlis',
  group: 'saugumas',
  value: 'saugumo-seselis',
  longDescription: 'Funkcija, leidžianti aktyvuoti ar deaktyvuoti saugumo šešėlį.',
  shortDescription: '',
  },
  {
  name: 'Saugumo režimas',
  group: 'saugumas',
  value: 'saugumo-rezimas',
  longDescription: 'Funkcija, skirta įjungti/išjungti saugumo režimą.',
  shortDescription: '',
  },
  {
  name: 'Sirena',
  group: 'saugumas',
  value: 'sirena',
  longDescription: 'Funkcija, skirta valdyti sireną.',
  shortDescription: '',
  },
  {
  name: 'Pranešimai',
  group: 'pranešimai',
  value: 'pranesimai',
  longDescription: 'Funkcija, skirta siųsti pranešimus naudotojui.',
  shortDescription: '',
  },
  {
  name: 'Pranešimai pagal laiką',
  group: 'pranešimai',
  value: 'pranesimai-pagal-laika',
  longDescription: 'Funkcija, skirta siųsti pranešimus naudotojui pagal nustatytą laiką.',
  shortDescription: '',
  },
  {
  name: 'Pranešimai pagal įvykius',
  group: 'pranešimai',
  value: 'pranesimai-pagal-ivykius',
  longDescription: 'Funkcija, skirta siųsti pranešimus naudotojui pagal tam tikrus įvykius.',
  shortDescription: '',
  },
  {
  name: 'Išoriniai įvykiai',
  group: 'pranešimai',
  value: 'isoriniai-ivykiai',
  longDescription: 'Funkcija, skirta siųsti pranešimus naudotojui apie išorinius įvykius.',
  shortDescription: '',
  },
  {
  name: 'Pranešimai įvairiomis kalbomis',
  group: 'pranešimai',
  value: 'pranesimai-ivairiomis-kalbomis',
  longDescription: 'Funkcija, skirta siųsti pranešimus naudotojui įvairiomis kalbomis.',
  shortDescription: '',
  },
  {
  name: 'Skambučių funkcijos',
  group: 'komunikacija',
  value: 'skambuciu-funkcijos',
  longDescription: 'Funkcija, skirta valdyti skambučių funkcijas (gavimas, perdavimas, blokavimas, užregistruoti pranešimus).',
  shortDescription: '',
  },
  {
  name: 'Garsų įrašymas',
  group: 'garso-irasymas',
  value: 'garsu-irasymas',
  longDescription: 'Funkcija, skirta įrašyti garsus.',
  shortDescription: '',
  },
  {
  name: 'Garsų atpažinimas',
  group: 'garso-atpazinimas',
  value: 'garsu-atpazinimas',
  longDescription: 'Funkcija, skirta atpažinti garsus.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas',
  longDescription: 'Funkcija, skirta atkurti garsus.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal laiką',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika',
  longDescription: 'Funkcija, skirta atkurti garsus pagal nustatytą laiką.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal įvykius',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-ivykius',
  longDescription: 'Funkcija, skirta atkurti garsus pagal tam tikrus įvykius.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal programą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-programa',
  longDescription: 'Funkcija, skirta atkurti garsus pagal tam tikrą programą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal vietą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal nustatytą vietą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal srautą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-srauta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal srautą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal turinį',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-turini',
  longDescription: 'Funkcija, skirta atkurti garsus pagal turinį.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą laiką',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika',
  longDescription: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą laiką.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą vietą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą vietą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą turinį',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-turini',
  longDescription: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą turinį.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą laiką ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą vietą ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą vietą ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, vietą ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-vieta-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, vietą ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą laiką, vietą ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-vieta-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką, vietą ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą laiką, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką, turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą vietą, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą vietą, turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką, vietą ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-vieta-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką, vietą ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką, turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, vietą, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-vieta-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, vietą, turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą laiką, vietą, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-vieta-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką, vietą, turinį ir kontekstą.',
  shortDescription: '',
  },
  {
  name: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką, vietą, turinį ir kontekstą',
  group: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-vieta-turini-konteksta',
  longDescription: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką, vietą, turinį ir kontekstą.',
  shortDescription: '',
  },
  ];
module.exports = { functionalitiesToAdd };