const functionalitiesToAdd = [
  {
    pavadinimas: 'Apšvietimo jungimas',
    sritis: 'Apšvietimas',
    aprasymas: 'Apšvietimo jungimo funkcija.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Apšvietimo šviesumo reguliavimas',
    sritis: 'Apšvietimas',
    aprasymas: 'Apšvietimo šviesumo reguliavimo funkcija.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Spalvos temperatūra',
    sritis: 'Apšvietimas',
    aprasymas: 'Apšvietimo spalvos temperatūros funkcija.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Spalva',
    sritis: 'Apšvietimas',
    aprasymas: 'Apšvietimo spalvos funkcija.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Sekos',
    sritis: 'Apšvietimas',
    aprasymas: 'Sekų funkcija.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Žaliuzės/Šalmai/Markizės/Vėdinimas',
    sritis: 'Langų ir durų valdymas',
    aprasymas: 'Funkcija, skirta valdyti žaliuzes, šalmus, markizes ir vėdinimą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Langai su grotomis',
    sritis: 'Langų ir durų valdymas',
    aprasymas: 'Funkcija, skirta valdyti langus su grotomis.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Ventiliacijos sklendės',
    sritis: 'Langų ir durų valdymas',
    aprasymas: 'Funkcija, skirta valdyti ventiliacijos sklendes.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Saugumas',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, skirta stebėti ir reaguoti į įvairias saugumo grėsmes, tokias kaip audros, lietus, nuotėkis, kondensacija ir CO2 koncentracija.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Audrų/lietaus stebėjimo sistema (satelitinė įranga)',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, skirta stebėti audrų ir lietaus intensyvumą ir reaguoti į juos.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Audrų/lietaus stebėjimo sistema (universalus siuntėjas)',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, skirta stebėti audrų ir lietaus intensyvumą ir reaguoti į juos.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Nuotėkio jutiklis',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, skirta aptikti vandens nuotėkį ir pranešti apie jį.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Kondensacijos jutiklis',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, skirta aptikti kondensacijos buvimą ir pranešti apie jį.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'CO2 jutiklis',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, skirta matuoti CO2 koncentraciją ir pranešti apie jos padidėjimą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Radiatorių termostatas',
    sritis: 'Šildymas/ventiliacija/oro kondicionavimas',
    aprasymas: 'Funkcija, leidžianti reguliuoti radiatoriaus temperatūrą pagal nustatytus parametrus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Sieninis termostatas',
    sritis: 'Šildymas/ventiliacija/oro kondicionavimas',
    aprasymas: 'Funkcija, skirta kontroliuoti bendrą kambario temperatūrą, naudojant sieninis termostatas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'šildymas',
    sritis: 'Šildymas/ventiliacija/oro kondicionavimas',
    aprasymas: 'Funkcija, reguliuojanti šildymo sistemą, kurią kontroliuoja šiluma.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Grindų šildymas',
    sritis: 'Šildymas/ventiliacija/oro kondicionavimas',
    aprasymas: 'Funkcija, reguliuojanti grindų šildymo sistemą pagal nustatytus parametrus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Ventiliacija',
    sritis: 'Šildymas/ventiliacija/oro kondicionavimas',
    aprasymas: 'Funkcija, reguliuojanti ventiliacijos sistemą namuose.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Scenos per sieninis siuntėjas',
    sritis: 'Scenos',
    aprasymas: 'Funkcija, leidžianti aktyvuoti scenas naudojant sieninį siuntėją.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Scenos per programėlę',
    sritis: 'Scenos',
    aprasymas: 'Funkcija, leidžianti aktyvuoti scenas naudojant mobiliosios programėlės sąsają.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Scenos per balsą',
    sritis: 'Scenos',
    aprasymas: 'Funkcija, leidžianti aktyvuoti scenas naudojant balsinį valdymą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Iki 34 scenų',
    sritis: 'Scenos',
    aprasymas: 'Funkcija, leidžianti sukurti ir valdyti iki 34 skirtingas scenas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Daugiau nei 100 scenų',
    sritis: 'Scenos',
    aprasymas: 'Funkcija, leidžianti sukurti ir valdyti daugiau nei 100 skirtingų scenas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Neribotas scenų kiekis',
    sritis: 'Scenos',
    aprasymas: 'Funkcija, leidžianti sukurti ir valdyti neribotą kiekį skirtingų scenų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Energijos matavimas',
    sritis: 'Energija',
    aprasymas: 'Funkcija, leidžianti matuoti energijos suvartojimą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'SENEC.Home baterijos saugojimas',
    sritis: 'Energija',
    aprasymas: 'Funkcija, skirta saugoti energiją SENEC namų baterijoje.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Oras - orų prognozė',
    sritis: 'Oras',
    aprasymas: 'Funkcija, leidžianti gauti orų prognozes.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Orų stotis',
    sritis: 'Oras',
    aprasymas: 'Funkcija, leidžianti gauti informaciją iš orų stoties.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Taisyklių kūrimas, pavyzdžiui, audroms',
    sritis: 'Oras',
    aprasymas: 'Funkcija, skirta kurti taisykles, pavyzdžiui, audroms.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Langų ir durų stebėjimas',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, leidžianti stebėti langų ir durų būklę.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Langų kontaktai',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, kuri praneša apie langų būklę.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Durų kontaktai',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, kuri praneša apie durų būklę.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Spynos jungiklių kontaktai',
    sritis: 'Saugumas',
    aprasymas: 'Funkcija, kuri praneša apie spynos būklę.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Reikšmių rodymas',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo įvairias reikšmes.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Apšvietimo intensyvumas (lux)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo apšvietimo intensyvumą luxais.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Temperatūra (°C)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo temperatūrą laipsniais Celsijaus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Galia (W)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo galios suvartojimą vatų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Energijos suvartojimas (kWh)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo energijos suvartojimą kilovatvalandėmis.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Drėgmė (g/m³)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo drėgmę gramais kubiniame metrų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'CO² koncentracija (ppm)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo anglies dioksido koncentraciją ppm (dalių per milijoną).',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Autonomija (%)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo autonomijos lygį procentais.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Darbo valandos (h)',
    sritis: 'Informacija',
    aprasymas: 'Funkcija, kuri rodo įrenginio darbo valandas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Laikmačiai su laiko juosta (įskaitant Astro funkciją)',
    sritis: 'Valdymas',
    aprasymas: 'Funkcija, kuri leidžia nustatyti laikmačius su laiko juosta ir įtraukti Astro funkciją.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: '40 laikmačių nustatymo kartai',
    sritis: 'Valdymas',
    aprasymas: 'Funkcija, kuri leidžia nustatyti iki 40 laikmačių nustatymo kartų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Astro funkcija',
    sritis: 'Valdymas',
    aprasymas: 'Funkcija, kuri leidžia naudoti astronominius laiko nustatymus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Iki 100 laikmačių nustatymo kartai',
    sritis: 'Valdymas',
    aprasymas: 'Funkcija, kuri leidžia nustatyti iki 100 laikmačių nustatymo kartų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Iki 250 laikmačių nustatymo kartai',
    sritis: 'Valdymas',
    aprasymas: 'Funkcija, kuri leidžia nustatyti iki 250 laikmačių nustatymo kartų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Iki 256 laikmačių nustatymo kartai',
    sritis: 'Valdymas',
    aprasymas: 'Funkcija, kuri leidžia nustatyti iki 256 laikmačių nustatymo kartų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Vartotojo galimybės konfigūruoti',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti vartotojui konfigūruoti įvairius nustatymus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Laikmatis',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti laiko programas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Įjungimo ryškumas',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti įjungimo ryškumą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Minimalus/maksimalus ryškumas',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti minimalų/maksimalų ryškumą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Įjungimo/išjungimo uždelsimas',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti įjungimo/išjungimo uždelsimą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Judesio jutiklio aptikimo sritys',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti judesio jutiklio aptikimo sritis.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Naktinis apšvietimas',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti naktinio apšvietimo funkciją.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Viešbučio funkcija',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti viešbučio funkciją.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Mėgstamiausi',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti mėgstamiausius nustatymus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Scenos',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti scenas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Taisyklės',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti taisykles.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Laikmatis',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti laiko programas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Balso paslauga',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti balso paslaugą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Nuotolinis prieiga',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti nuotolinę prieigą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'tado° šildymo sprendimas',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti valdyti tado° šildymo sprendimą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Mėgstamiausi',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti mėgstamiausius nustatymus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Scenos',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti scenas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Taisyklės (veiksmai)',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti taisyklių veiksmus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Laikmatis',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti laiko programas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Balso paslauga',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti balso paslaugą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Nuotolinis prieiga',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti nuotolinę prieigą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Philips Hue',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti valdyti Philips Hue įrangą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Sonos',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti valdyti Sonos įrangą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Scenos',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti scenas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Taisyklės',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti taisykles.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Laikmatis',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti nustatyti laiko programas.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Balso paslauga',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti balso paslaugą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Nuotolinis prieiga',
    sritis: 'Konfigūracija',
    aprasymas: 'Funkcija, leidžianti naudoti nuotolinę prieigą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Vartotojo valdymas',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Funkcija, leidžianti valdyti vartotojus ir jų leidimus sistemoje.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Vartotojas',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Vartotojas su standartiniais leidimais.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Slaptažodis',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Funkcija, leidžianti nustatyti slaptažodį vartotojo paskyrai.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Administratorius',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Vartotojas su visais valdymo leidimais sistemoje.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Vartotojas su keitimo leidimais',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Vartotojas, kuriam leidžiama keisti tam tikrus nustatymus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Vartotojas be keitimo leidimų',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Vartotojas, kuriam neleidžiama keisti nustatymų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Administratorius su laisvai nustatomais leidimais',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Administratorius su galimybe laisvai nustatyti vartotojų leidimus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Iki 24 vartotojai su laisvai nustatomais leidimais',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Sistema, leidžianti sukurti iki 24 vartotojus su laisvai nustatomais leidimais.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Administratorius su laisvai nustatomais leidimais',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Administratorius su galimybe laisvai nustatyti vartotojų leidimus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Iki 150 vartotojų su laisvai nustatomais leidimais',
    sritis: 'Vartotojų valdymas',
    aprasymas: 'Sistema, leidžianti sukurti iki 150 vartotojų su laisvai nustatomais leidimais.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Buvimo simuliacija',
    sritis: 'Saugumo sistemos',
    aprasymas: 'Funkcija, kuri naudoja įrenginio atmintį ir laiko programavimą, norint sukurti buvimo simuliaciją. Galima sukurti simuliaciją, kuri tęsis 24 valandas, ir kuri naudos laiko programavimo funkciją. Taip pat galima sukurti specifiškai sukurtą simuliaciją, įtraukiant atsitiktinę funkciją.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Atsitiktinė buvimo simuliacija',
    sritis: 'Saugumo sistemos',
    aprasymas: 'Buvimo simuliacija, kurioje naudojamas atsitiktinės funkcijos elementas, kuris suteikia įspūdį, kad namuose yra žmonių, net kai jie nėra.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Logikos funkcijos (jeigu-tada)',
    sritis: 'Logikos funkcijos',
    aprasymas: 'Ši funkcija leidžia nustatyti iki 32 jeigu-tada sąlygas su galimybe naudoti operatorius AND, OR ir XOR. Taip pat galima sukurti iki 250 jeigu-tada sąlygas su operatoriais AND, OR ir XOR. Šios funkcijos taip pat leidžia naudoti papildomas funkcijas, tokiu kaip skaitiklis, asmeniniai scenarijai ir neribojama jeigu-tada sąlygų kiekis.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Logikos funkcijos (jeigu-tada)',
    sritis: 'Logikos funkcijos',
    aprasymas: 'Ši funkcija leidžia nustatyti iki 32 jeigu-tada sąlygas su galimybe naudoti operatorius AND, OR ir XOR. Taip pat galima sukurti iki 250 jeigu-tada sąlygas su operatoriais AND, OR ir XOR. Šios funkcijos taip pat leidžia naudoti papildomas funkcijas, tokiu kaip skaitiklis, asmeniniai scenarijai ir neribojama jeigu-tada sąlygų kiekis.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Automatinis apšvietimo valdymas',
    sritis: 'apšvietimas',
    value: 'automatinis-apsvietimo-valdymas',
    aprasymas: 'Ši funkcija leidžia automatizuoti namų apšvietimą, taikant įvairius scenarijus ir valdymo būdus. Ji leidžia nustatyti apšvietimo lygį priklausomai nuo dienos laiko, judesio ar kitų parametrų. Tai ne tik padeda sutaupyti energiją, bet ir užtikrina patogumą ir saugumą.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Garso sistema',
    sritis: 'bendra',
    value: 'garso-sistema',
    aprasymas: 'Garso sistema yra funkcija, kuri leidžia vartotojams valdyti garsą įvairiuose namo zonuose. Tai apima galimybę valdyti garsiakalbius, ausines ar net integraciją su "smart" televizoriais. Garso sistemos funkcionalumas gali būti integruotas su kitomis namų automatizavimo sistemomis, suteikiant plačias galimybes namų pramogų ir patogumo srityse.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Vartotojo buvimo sekimas',
    sritis: 'saugos-sistemos',
    value: 'vartotojo-buvimo-sekimas',
    aprasymas: 'Vartotojo buvimo sekimas yra funkcija, kuri naudoja judesio jutiklius nustatyti, kada žmonės yra namuose arba išvykę. Tai leidžia stebėti ir valdyti namo saugumą bei efektyviai naudoti energiją, nustatant įspėjimus arba automatizuotus veiksmus priklausomai nuo vartotojų buvimo.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Klimato valdymas, inžinerinės sistemos',
    sritis: 'klimato-valdymas-inzinerines-sistemos',
    value: 'klimato-valdymas-inzinerines-sistemos',
    aprasymas: 'Ši funkcija leidžia valdyti klimato parametrus namuose, įskaitant temperatūrą, drėgmę ir oro srautus. Ji taip pat integruojama su inžinerinėmis sistemomis, tokiomis kaip šildymas, vėdinimas ir oro kondicionavimas, siekiant užtikrinti optimalią aplinką vartotojams.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Apšvietimas išmaniuosiuose namuose',
    sritis: 'apsvietimas-ismaniuosiuose-namuose',
    value: 'apsvietimas-ismaniuosiuose-namuose',
    aprasymas: 'Ši funkcija leidžia valdyti apšvietimo sistemos veikimą išmaniuose namuose naudojant įvairias technologijas, tokias kaip LED šviesos šaltiniai ir išmanieji jungikliai. Tai ne tik suteikia vartotojams galimybę reguliuoti apšvietimo lygį ir atmosferą, bet ir padeda taupyti energiją.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Langų ir žaliuzių valdymas',
    sritis: 'langu-ir-zaliuziu-valdymas',
    value: 'langu-ir-zaliuziu-valdymas',
    aprasymas: 'Ši funkcija leidžia valdyti langų ir žaliuzių veikimą išmaniuose namuose, naudojant automatizavimo technologijas. Tai apima galimybę atidaryti, uždaryti ar net reguliuoti langų atspalvį ir skaidrumą, taip pat valdyti žaliuzes priklausomai nuo dienos laiko ar išorės sąlygų.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Saugos sistemos',
    sritis: 'saugos-sistemos',
    value: 'saugos-sistemos',
    aprasymas: 'Ši funkcija apima visus saugos sistemų komponentus ir funkcionalumus, skirtus apsaugoti namą ir gyventojus nuo įvairių pavojų, įskaitant vagystes, gaisrus ir nelaimingus atsitikimus. Tai apima judesio jutiklius, vaizdo stebėjimo kameras, dujų ir dūmų detektorius bei kitus saugos prietaisus.',
    trumpas_aprasymas: '',
  },
  {
    pavadinimas: 'Komforto įranga',
    sritis: 'komforto-iranga',
    value: 'komforto-iranga',
    aprasymas: 'Ši funkcija apima įvairius įrangos sprendimus, kurie padeda padidinti vartotojų komfortą ir patogumą namuose. Tai gali būti susiję su ergonomiškomis baldų išdėstymo schemomis, specializuotomis patogumo funkcijomis ar net automatizuotomis kasdieninėmis veiklomis.',
   trumpas_aprasymas: 'Funkcija skirta didinti komfortą ir patogumą namuose.',
  },
  {
    pavadinimas: 'Energijos šaltiniai',
    sritis: 'energijos-saltiniai',
    value: 'energijos-saltiniai',
    aprasymas: 'Ši funkcija apima skirtingus energijos tiekimo šaltinius, kurie gali būti naudojami namuose, įskaitant elektrą, dujas, saulės energiją ir kt. Tai leidžia vartotojams pasirinkti efektyviausią ir tvariausią energijos šaltinį, atsižvelgiant į jų poreikius ir aplinkosaugos aspektus.',
    trumpas_aprasymas: 'Funkcija skirta energijos tiekimo šaltinių valdymui namuose.',
  },
  {
  pavadinimas: 'Apšvietimo jungiklis',
  sritis: 'apšvietimas',
  value: 'apsvietimo-jungiklis',
  aprasymas: 'Funkcija, skirta valdyti apšvietimą - įjungti/išjungti.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Apšvietimo reguliavimas',
  sritis: 'apšvietimas',
  value: 'apsvietimo-reguliavimas',
  aprasymas: 'Funkcija, leidžianti reguliuoti apšvietimo intensyvumą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Šviesos temperatūros reguliavimas',
  sritis: 'apšvietimas',
  value: 'sviesos-temperaturos-reguliavimas',
  aprasymas: 'Funkcija, leidžianti reguliuoti šviesos spalvą ar temperatūrą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Spalvos reguliavimas',
  sritis: 'apšvietimas',
  value: 'spalvos-reguliavimas',
  aprasymas: 'Funkcija, skirta valdyti apšvietimo spalvą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Sekos',
  sritis: 'apšvietimas',
  value: 'sekos',
  aprasymas: 'Funkcija, skirta kurti sekas apšvietimui.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Žaliuzės',
  sritis: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'zaliuzes',
  aprasymas: 'Funkcija, skirta valdyti žaliuzes.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Šutteriai',
  sritis: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'sutteriai',
  aprasymas: 'Funkcija, skirta valdyti šutterius.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Markizės',
  sritis: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'markizes',
  aprasymas: 'Funkcija, skirta valdyti markizes.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Ventiliacijos sklendės',
  sritis: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'ventiliacijos-sklendes',
  aprasymas: 'Funkcija, skirta valdyti ventiliacijos sklendes.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Langų stogai',
  sritis: 'žaliuzės-šutteriai-markizės-ventiliacija-langų-stogai',
  value: 'langus-stogai',
  aprasymas: 'Funkcija, skirta valdyti langų stogus.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Saugumo šešėlis',
  sritis: 'saugumas',
  value: 'saugumo-seselis',
  aprasymas: 'Funkcija, leidžianti aktyvuoti ar deaktyvuoti saugumo šešėlį.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Saugumo režimas',
  sritis: 'saugumas',
  value: 'saugumo-rezimas',
  aprasymas: 'Funkcija, skirta įjungti/išjungti saugumo režimą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Sirena',
  sritis: 'saugumas',
  value: 'sirena',
  aprasymas: 'Funkcija, skirta valdyti sireną.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Pranešimai',
  sritis: 'pranešimai',
  value: 'pranesimai',
  aprasymas: 'Funkcija, skirta siųsti pranešimus naudotojui.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Pranešimai pagal laiką',
  sritis: 'pranešimai',
  value: 'pranesimai-pagal-laika',
  aprasymas: 'Funkcija, skirta siųsti pranešimus naudotojui pagal nustatytą laiką.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Pranešimai pagal įvykius',
  sritis: 'pranešimai',
  value: 'pranesimai-pagal-ivykius',
  aprasymas: 'Funkcija, skirta siųsti pranešimus naudotojui pagal tam tikrus įvykius.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Išoriniai įvykiai',
  sritis: 'pranešimai',
  value: 'isoriniai-ivykiai',
  aprasymas: 'Funkcija, skirta siųsti pranešimus naudotojui apie išorinius įvykius.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Pranešimai įvairiomis kalbomis',
  sritis: 'pranešimai',
  value: 'pranesimai-ivairiomis-kalbomis',
  aprasymas: 'Funkcija, skirta siųsti pranešimus naudotojui įvairiomis kalbomis.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Skambučių funkcijos',
  sritis: 'komunikacija',
  value: 'skambuciu-funkcijos',
  aprasymas: 'Funkcija, skirta valdyti skambučių funkcijas (gavimas, perdavimas, blokavimas, užregistruoti pranešimus).',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garsų įrašymas',
  sritis: 'garso-irasymas',
  value: 'garsu-irasymas',
  aprasymas: 'Funkcija, skirta įrašyti garsus.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garsų atpažinimas',
  sritis: 'garso-atpazinimas',
  value: 'garsu-atpazinimas',
  aprasymas: 'Funkcija, skirta atpažinti garsus.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas',
  aprasymas: 'Funkcija, skirta atkurti garsus.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal laiką',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal nustatytą laiką.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal įvykius',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-ivykius',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal tam tikrus įvykius.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal programą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-programa',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal tam tikrą programą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal vietą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal nustatytą vietą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal srautą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-srauta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal srautą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal turinį',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-turini',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal turinį.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą laiką',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą laiką.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą vietą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą vietą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą turinį',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-turini',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą turinį.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal nustatytą naudotojo valdomą kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą laiką ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą vietą ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą vietą ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, vietą ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-vieta-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, vietą ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą laiką, vietą ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-vieta-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką, vietą ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą laiką, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą vietą, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-vieta-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą vietą, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką, vietą ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-vieta-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką, vietą ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, vietą, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-vieta-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, vietą, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą laiką, vietą, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-laika-vieta-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą laiką, vietą, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  {
  pavadinimas: 'Garso atkūrimas pagal naudotojo valdomą sąrašą, laiką, vietą, turinį ir kontekstą',
  sritis: 'garso-atkūrimas',
  value: 'garso-atkurimas-pagal-sarasa-laika-vieta-turini-konteksta',
  aprasymas: 'Funkcija, skirta atkurti garsus pagal naudotojo valdomą sąrašą, laiką, vietą, turinį ir kontekstą.',
  trumpas_aprasymas: '',
  },
  ];
module.exports = { functionalitiesToAdd };