const functionalitiesToAdd = [
  {
    name: 'Apšvietimo jungimas',
    group: 'apsvietimas',
    longDescription: 'tai procesas, kai elektrinė įranga arba prietaisai yra įjungiami arba išjungiami. Šis procesas gali būti atliekamas rankiniu būdu, naudojant mechaninius arba elektroninius įrenginius, arba automatiškai, pagal tam tikrus nustatytus sąlygų ar veikimo principų. ',
    shortDescription: '',
  },
  {
    name: 'Apšvietimo šviesumo reguliavimas',
    group: 'apsvietimas',
    longDescription: 'tai  procesas, kai reguliuojama šviesos šaltinio išspinduliavimo galia, kad būtų pasiektas norimas šviesos lygis. Tai gali būti atliekama naudojant specialius įtaisus arba technologijas, kurios keičia elektros srovės įtampą arba dažnį, taip mažindamos ar didindamos šviesos stiprumą.',
    shortDescription: '',
  },
  {
    name: 'Spalvos temperatūra',
    group: 'apsvietimas',
    longDescription: 'tai yra matavimas, skirtas apibūdinti šviesos spalvą, kuri yra išreikšta Kelvinų (K) skalėje. Ji apibūdina šviesos šaltinio spektrinį sudėjimą ir yra susijusi su spalvos tonu, kuriame šviesos šaltinis spinduliuoja.',
    shortDescription: '',
  },
  {
    name: 'Spalva',
    group: 'apsvietimas',
    longDescription: 'tai yra svarbi funkcija šviesos apšvietime, nes ji nulemia objekto arba scenos vizualinį įspūdį. Šviesos spalva priklauso nuo šviesos šaltinio spektrinio turinio ir apšvietimo aplinkos.',
    shortDescription: '',
  },
  {
    name: 'Sekos',
    group: 'apsvietimas',
    longDescription: '- sviesos apšvietime gali būti suprantama kaip iš anksto nustatytas šviesos šaltinio veiksmų arba šviesos šviesos efektų serijos. Tai gali apimti šviesos šaltinio įjungimą arba išjungimą tam tikru laiku, spalvų perėjimą, šviesos stiprumo pokyčius, judančius šviesos efektus ir kitus šviesos pokyčius. ',
    shortDescription: '',
  },
  {
    name: 'Užuolaidos',
    group: 'langu-ir-duru-valdymas',
    longDescription: 'šviesos apšvietime gali būti naudojamos kaip funkcija, leidžianti kontroliuoti šviesos kryptį arba intensyvumą. Šviesos žaliuzės arba lankstūs šviesos elementai gali būti reguliuojami, kad būtų pasiekta norima šviesos skleidimo kryptis arba plotas.',
    shortDescription: '',
  },
  {
    name: 'Žaliuzės',
    group: 'langu-ir-duru-valdymas',
    longDescription: 'šviesos apšvietime gali būti naudojamos kaip funkcija, leidžianti reguliuoti šviesos srautą arba intensyvumą. Šviesos skliautai yra reguliuojami lanksčios konstrukcijos elementai, kurie gali būti atidaromi arba uždaromi, siekiant kontroliuoti šviesos kiekį, kuris patenka į tam tikrą erdvę arba objektą.',
    shortDescription: '',
  },
  {
    name: 'Markizės',
    group: 'langu-ir-duru-valdymas',
    longDescription: 'tai  yra apsauginiai ir dekoratyviniai elementai, kurie dedami virš langų, durų ar terasų, siekiant apsaugoti nuo tiesioginių saulės spindulių arba lietaus.',
    shortDescription: '',
  },
  {
    name: 'Stoglangiai',
    group: 'langu-ir-duru-valdymas',
    longDescription: 'tai yra specialios lango formos konstrukcijos, kurios įmontuojamos į stogą ir leidžia natūraliam šviesos srautui patenkinti į patalpas iš viršaus. Šios šviesos elementai gali būti statomos iš stiklo arba plastiko ir paprastai yra dizainuotos taip, kad būtų atsparios vandeniui.',
    shortDescription: '',
  },
  {
    name: 'Langai su grotomis',
    group: 'langu-ir-duru-valdymas',
    longDescription: 'Funkcija, skirta valdyti langus su grotomis.',
    shortDescription: '',
  },
  {
    name: 'Vėdinimo sklendės',
    group: 'langu-ir-duru-valdymas',
    longDescription: 'tai yra elementai, kurie leidžia reguliuoti oro srautą tarp vidaus ir išorės.',
    shortDescription: '',
  },
  {
    name: 'Apsauga',
    group: 'apsauga',
    longDescription: 'smart namų sistemoje yra svarbi funkcija, skirta užtikrinti gyventojų ir jų turtų apsaugą. Ši funkcija apima įvairius įrankius ir technologijas, kurios leidžia atpažinti ir reaguoti į bet kokius potencialius pavojus ar nesklandumus. ',
    shortDescription: '',
  },
  {
    name: 'Audrų lietaus stebėjimo sistema (palydovinis įrenga)',
    group: 'apsauga',
    longDescription: 'gali būti vertinama kaip speciali prietaiso dalis, kuri yra integruota į smart home sistemą ir skirta stebėti oro sąlygas, ypač susijusias su audromis ir lietumi. Ši prietaiso dalis gali būti susijusi su meteorologinėmis stebėsenos sistemomis arba gauti informaciją iš meteorologinių palydovų.',
    shortDescription: '',
  },
  {
    name: 'Audrų lietaus stebėjimo sistema (universalus siųstuvas)',
    group: 'apsauga',
    longDescription: 'gali būti vertinama kaip įrenginys, skirtas detaliai stebėti oro sąlygas, ypač susijusias su audromis ir lietumi, ir siųsti šią informaciją į smart home sistemą. Šis universalus perdaviklis gali būti susijęs su įvairiomis meteorologinėmis stebėsenos sistemomis arba palydovinėmis tarnybomis, kurios teikia informaciją apie orus.',
    shortDescription: '',
  },
  {
    name: 'Nuotėkis',
    group: 'apsauga',
    longDescription: 'smart home sistemoje gali būti vertinama kaip funkcija, skirta aptikti vandens nutekėjimus arba nuotėkį namų viduje ir nedelsiant pranešti apie tai gyventojams. Ši funkcija gali būti įgyvendinta naudojant specialius vandens jutiklius arba sensorius, kurie yra įdiegti tam tikruose strategiškai svarbiuose vietose, tokiuose kaip virtuvės, vonios kambariai, skalbimo mašinos arba kiti vandens naudojimo taškai.',
    shortDescription: '',
  },
  {
    name: 'Kondensatas',
    group: 'apsauga',
    longDescription: 'smart home sistemoje gali būti suprantama kaip funkcija, skirta aptikti kondensacijos atsiradimą ir valdyti tai susijusius veiksmus. Kondensacija yra procesas, kai oro drėgmė prisikerta ant šalto paviršiaus, pavyzdžiui, langų ar veidrodžių, ir virsta vandens lašais arba rūkeliu. Šis reiškinys gali sukelti ne tik estetinę problemą, bet ir potencialią pavojų namo interjero kokybei ir struktūros pažeidimą.',
    shortDescription: '',
  },
  {
    name: 'CO2',
    group: 'apsauga',
    longDescription: 'smart home sistemoje gali būti suprantama kaip funkcija, skirta aptikti anglies dioksido lygį patalpose ir įvairiais būdais valdyti oro kokybę.',
    shortDescription: '',
  },
  {
    name: 'Radiatorių termostatas',
    group: 'sildymas-ventiliacija-oro-kondicionavimas',
    longDescription: 'smart home sistemoje yra funkcija, kuri leidžia valdyti šildymo sistemos radiatorius naudojant išmaniuosius termostatus. Šis termostatas yra įdiegtas ant radiatoriaus ir gali būti valdomas išmaniajame telefone arba kitaip integruotoje sistemoje.Pagrindinė radiatoriaus termostato funkcija yra reguliuoti kambario temperatūrą, valdydama radiatoriaus šilumos išmetimą. Tai leidžia gyventojams individualiai nustatyti kiekvieno kambario temperatūrą ir taupyti energiją, nes galima nustatyti optimalų šilumos lygį kiekvienam kambaryje atsižvelgiant į jo naudojimąsi ir asmeninius poreikius.',
    shortDescription: '',
  },
  {
    name: 'Sieninis termostatas',
    group: 'sildymas-ventiliacija-oro-kondicionavimas',
    longDescription: 'tai yra įrenginys, kuris montuojamas ant sienos ir naudojamas valdyti kambario temperatūrą. Tai gali būti svarbi funkcija smart home sistemoje.Pagrindinė sieninio termostato funkcija yra reguliuoti šildymo arba vėdinimo sistemą, kad būtų išlaikytas pageidaujamas kambario temperatūros lygis. Įrenginys gali būti valdomas rankiniu būdu, naudojant jo fizinį ekraną ir mygtukus, arba automatiškai, pagal nustatytus grafikus arba scenarijus.',
    shortDescription: '',
  },
  {
    name: 'Boileris',
    group: 'sildymas-ventiliacija-oro-kondicionavimas',
    longDescription: 'tai yra svarbus prietaisas šildymo sistemoje, kuris naudojamas šildyti vandenį. Tai svarbi funkcija smart home sistemoje, nes leidžia valdyti šildymo sistemą ir vandens šildymą, kad būtų optimizuotas energijos naudojimas ir patogumas.',
    shortDescription: '',
  },
  {
    name: 'Grindų šildymas',
    group: 'sildymas-ventiliacija-oro-kondicionavimas',
    longDescription: 'tai yra šildymo sistema, kurioje šiluma yra paskirstoma per grindis, o ne per tradicinius radiatorius ar oro srautus. Tai svarbi funkcija smart home sistemoje, nes leidžia valdyti kambario temperatūrą efektyviai ir komfortiškai.',
    shortDescription: '',
  },
  {
    name: 'Ventiliacija',
    group: 'sildymas-ventiliacija-oro-kondicionavimas',
    longDescription: 'tai yra svarbi funkcija smart home sistemoje, skirta valdyti oro cirkuliaciją ir kokybę patalpose.',
    shortDescription: '',
  },
  {
    name: 'Scenos per sieninį perdavėją ',
    group: 'scenos',
    longDescription: 'tai reiškia, kad per sieninį perdavėją (pultelį) galima valdyti skirtingus scenarijus arba nustatymus smart home sistemoje. scenos gali apimti įvairius veiksmus, pvz., reguliuoti apšvietimą, temperatūrą, uždaryti ar atidaryti žaliuzes ir kt. Sieninis perdavėjas suteikia patogumą ir greitą prieigą prie įvairių namo funkcijų, leisdamas greitai prisitaikyti prie gyvenimo būdo ar pageidavimų.',
    shortDescription: '',
  },
  {
    name: 'Scenos per programėlę',
    group: 'scenos',
    longDescription: 'tai reiškia, kad per mobiliąją aplikaciją galima valdyti skirtingus scenarijus arba nustatymus smart home sistemoje. scenos gali apimti įvairius veiksmus, pvz., įjungti ar išjungti apšvietimą, reguliuoti temperatūrą, valdyti saugumo sistemas ir kt. Mobili aplikacija suteikia patogumą ir galimybę valdyti namo funkcijas iš bet kurios vietos, kur yra interneto ryšys.',
    shortDescription: '',
  },
  {
    name: 'Scenos per balsų valdymą ',
    group: 'scenos',
    longDescription: 'tai reiškia, kad galima valdyti skirtingus scenarijus ar nustatymus smart home sistemoje naudojant balso komandas arba balsų asistentus, tokius kaip "Alexa" ar "Google Assistant". Ši funkcija leidžia vartotojams aktyvuoti norimus scenarijus ar nustatymus, tiesiog kalbant į įrenginį, kuris turi integruotą balso valdymo technologiją.',
    shortDescription: '',
  },
  {
    name: 'Iki 34 scenų',
    group: 'scenos',
    longDescription: 'tai reiškia, kad yra galimybė sukurti arba programuoti iki 34 skirtingus scenarijus arba nustatymus smart home sistemoje. Šios scenos gali apimti įvairius veiksmus, tokius kaip įjungti/arba išjungti apšvietimą, reguliuoti temperatūrą, valdyti saugumo sistemas ir pan. Tai suteikia vartotojams didelį lankstumą ir galimybes pritaikyti savo namų automatizavimą pagal asmeninius poreikius ir gyvenimo būdą.',
    shortDescription: '',
  },
  {
    name: 'Daugiau nei 100 scenų',
    group: 'scenos',
    longDescription: 'tai reiškia, kad yra galimybė sukurti arba programuoti daugiau nei 100 skirtingų scenarijų ar nustatymų smart home sistemoje. Šios scenos gali apimti įvairius veiksmus, pavyzdžiui, įjungti ar išjungti apšvietimą, reguliuoti temperatūrą, valdyti saugumo sistemas ir t.t. Tai suteikia vartotojams labai didelį lankstumą ir galimybes pritaikyti savo namų automatizavimą pagal asmeninius poreikius ir gyvenimo būdą.',
    shortDescription: '',
  },
  {
    name: 'Neribotas scenų kiekis',
    group: 'scenos',
    longDescription: 'tai reiškia, kad nėra jokio apribojimo, kiek scenų galima sukurti arba programuoti smart namų sistemoje. Vartotojai gali kurti tiek scenų, kiek nori, ir pritaikyti jas pagal savo individualius poreikius bei gyvenimo būdą. Tai suteikia didelį lankstumą ir galimybes maksimaliai pritaikyti automatizavimą pagal jų norus ir aplinkybes.',
    shortDescription: '',
  },
  {
    name: 'Energijos matavimas',
    group: 'energija',
    longDescription: 'tai yra funkcija, kuri leidžia matuoti, stebėti ir įvertinti elektros energijos naudojimą namuose arba įrenginyje. Ši funkcija gali būti integruota į smart home sistemą ir suteikti vartotojui informaciją apie tai, kiek energijos naudojama, kada ji naudojama ir kaip ji gali būti efektyviau valdoma. Tai padeda vartotojams sekti jų energijos sąnaudas, identifikuoti taupymo galimybes ir padėti priimti informuotus sprendimus, siekiant sumažinti energijos sąnaudas ir išlaikyti efektyvų energijos naudojimą.',
    shortDescription: '',
  },
  {
    name: 'SENEC namų baterijos saugojimas',
    group: 'energija',
    longDescription: 'tai yra sistema, kuri leidžia saugoti perteklinę elektros energiją, pagamintą iš saulės ar kitų energijos šaltinių, naudojant baterijas. Ši sistema leidžia vartotojams naudoti saugotą energiją, kai jos reikia, pavyzdžiui, vakare ar rūsyje, kai saulė nenusileidžia arba elektros energijos poreikis yra didesnis. Tai padeda sumažinti elektros sąnaudas ir padidina savarankiškumą, naudojant alternatyvius energijos šaltinius.',
    shortDescription: '',
  },
  {
    name: 'Oro prognozė',
    group: 'oras',
    longDescription: 'tai yra informacija, kuri teikia numatytą orų būklę tam tikrame regione ateinančiomis dienomis ar valandomis. Ši informacija gali apimti temperatūrą, drėgmę, vėjo greitį ir kryptį, kritulių tikimybę ir kitus oro sąlygų rodiklius. Oro prognozės yra svarbios planuojant veiklą lauke arba pasiruošiant tam tikriems orų sąlygoms. Daugelis smart home sistemų gali įtraukti oro prognozės funkciją, kad vartotojams būtų lengviau planuoti jų dienas ir reguliuoti namų komfortą pagal numatytas orų sąlygas.',
    shortDescription: '',
  },
  {
    name: 'Oro stotelė',
    group: 'oras',
    longDescription: 'tai yra įrenginys, skirtas matuoti ir stebėti įvairius orų parametrus, tokiais kaip temperatūra, drėgmė, vėjo greitis ir kryptis, kritulių kiekis, slėgis ir kt. Oro stotelės gali būti naudojamos tiek asmeniniams, tiek komerciniams tikslams, teikianti išsamesnę ir tikslią informaciją apie orų sąlygas tam tikrame regione. Šios stotelės gali būti įdiegtos namų aplinkoje arba įvairiose vietose, pavyzdžiui, miestų centrų stoguose, oro uostuose, laivybose ar netgi kosminėse misijose. Taip pat įvairios smart home sistemos gali naudoti duomenis iš oro stotelės, kad būtų suteikta išsamesnė ir asmeniškesnė informacija apie orų sąlygas ir pagal tai prisitaikyti automatizuoti namų funkcijas.',
    shortDescription: '',
  },
  {
    name: 'Taisyklių kūrimas audrų atveju',
    group: 'oras',
    longDescription: 'tai reiškia sukurti nustatytas instrukcijas ar veiksmus, kurie bus vykdomi, kai įvyksta audros ar stiprūs atmosferos sąlygų pokyčiai.',
    shortDescription: '',
  },
  {
    name: 'Langų jutikliai',
    group: 'saugumas',
    longDescription: 'tai yra įrenginiai, kurie yra sumontuoti ant langų ar durų ir skirti aptikti jų atidarymą ar uždarymą. Šie jutikliai gali būti dalis saugumas ir leidžia vartotojams stebėti ir valdyti namų saugumą. Kai langai ar durys yra atidaromi, jutikliai gali išsiųsti signalą į centrinę kontrolės sistemą, kuri gali inicijuoti įvairius veiksmus, pavyzdžiui, įjungti apsaugos signalą arba pranešti vartotojams apie galimą pavojų. Tai padeda užtikrinti namų saugumą ir apsaugą nuo nepageidaujamų įsilaužimų arba nelaimingų atsitikimų.',
    shortDescription: '',
  },
  {
    name: 'Durų jutikliai',
    group: 'saugumas',
    longDescription: 'tai  yra įrenginiai, kurie montuojami ant durų ir skirti aptikti jų atidarymą ar uždarymą. Šie jutikliai yra svarbus komponentas saugumase ir leidžia vartotojams stebėti ir kontroliuoti durų būseną.Kai durys yra atidarytos ar uždarytos, jutikliai gali nustatyti šią būseną ir siųsti signalą į centralinę valdymo sistemą. Tai leidžia sistemos vartotojams gauti pranešimus apie durų būseną ir atlikti tam tikrus veiksmus, pavyzdžiui, įjungti arba išjungti saugumo funkcijas, registruoti durų naudojimo laiką arba prireikus pranešti apie nepageidaujamus įvykius, tokius kaip įsilaužimai.',
    shortDescription: '',
  },
  {
    name: 'Mirtino spynos jungiklių kontaktai',
    group: 'saugumas',
    longDescription: 'tai yra kontaktai, kurie yra susiję su mirtinės spynos mechanizmu. Mirtinoji spyna yra mechanizmas, kuris yra sumontuotas ant durų ir suteikia papildomą saugumą užrakindamas duris iš vidaus. Kai spyna yra įsijungiama arba išjungiama, šie kontaktai aptinka šią būseną ir gali siųsti signalą į centrinius valdymo sistemą.',
    shortDescription: '',
  },
  {
    name: 'Šviesumas (lux)',
    group: 'informacija',
    longDescription: 'tai yra vienetas, skirtas matuoti apšvietimo lygį arba šviesos intensyvumą. Tai reiškia, kiek šviesos yra apšviečiama tam tikroje vietoje arba plotelyje',
    shortDescription: '',
  },
  {
    name: 'Galia (W)',
    group: 'informacija',
    longDescription: 'Šis žymėjimas nurodo elektros energijos suvartojimo lygį arba galios kiekį, išreikštą vatais (W). Vatai yra matavimo vienetas, naudojamas apibrėžti elektros energijos arba energijos perdavimo greitį. Kai kalbama apie smart home sistemas ar kitus elektros prietaisus, galios matavimas leidžia vartotojams sužinoti, kiek energijos naudoja įrenginys, kas gali būti svarbu energijos taupymo ir efektyvumo tikslais. ',
    shortDescription: '',
  },
  {
    name: 'Energijos suvartojimas (kWh)',
    group: 'informacija',
    longDescription: 'Šis žymėjimas nurodo bendrą elektros energijos kiekį, kurį prietaisas ar sistema suvartojo per tam tikrą laikotarpį, išreikštą kilovatvalandėmis (kWh). Kilovatvalanda yra elektros energijos suvartojimo vienetas, kuris lygus 1 kW galios naudojimui per valandą.',
    shortDescription: '',
  },
  {
    name: 'Drėgmė (g/m³)',
    group: 'informacija',
    longDescription: 'tai  nurodo oro drėgnio lygį tam tikroje aplinkoje, išreikštą gramais drėgmės vienam kubiniam metrui oro (g/m³). Drėgmės matavimas yra svarbus parametras, kai kalbama apie oro kokybę ir komfortą, ypač indoor aplinkose.',
    shortDescription: '',
  },
  {
    name: 'CO2',
    group: 'informacija',
    longDescription: 'smart home sistemoje gali būti suprantama kaip funkcija, skirta aptikti anglies dioksido lygį patalpose ir įvairiais būdais valdyti oro kokybę.',
    shortDescription: '',
  },
  {
    name: 'Autarchijos lygis  (%)',
    group: 'informacija',
    longDescription: 'Šis terminas nurodo procentinį dalį ar santykį tarp pagamintos ar naudojamos energijos ir jos poreikio, kuris yra patenkinamas iš vidinių šaltinių arba šaltinių, priklausančių nuo savininko ar naudotojo. Kitaip tariant, tai rodo, kiek energijos vartotojas gali gaminti arba pateikti iš savo resursų, neprisijungdamas prie išorinių tiekėjų.',
    shortDescription: '',
  },
  {
    name: 'Veikimo valandos (h)',
    group: 'informacija',
    longDescription: 'tai nurodo bendrą laiką, per kurį prietaisas ar sistema buvo veikianti, išreikštą valandomis (h). Šis parametras svarbus norint įvertinti prietaiso ar sistemos naudojimą, nustatyti jo darbo trukmę arba vertinti jo veikimo efektyvumą.',
    shortDescription: '',
  },
  {
    name: 'Laikmačių jungikliai',
    group: 'valdymas',
    longDescription: 'tai yra įrenginiai, kurie leidžia nustatyti ir valdyti įvairių prietaisų, šviesos ar kitų elektrinių įrenginių veikimą pagal numatytus laiko nustatymus.',
    shortDescription: '',
  },
  {
    name: '40 jungimo laikų',
    group: 'valdymas',
    longDescription: 'tai reiškia, kad įrenginys ar sistema gali būti sukonfigūruota įvykdyti tam tikrą veiksmą (pavyzdžiui, įjungti ar išjungti prietaisą) iki 40 kartų tam tikru laiko tarpeliu.',
    shortDescription: '',
  },
  {
    name: 'Astro funkcija',
    group: 'valdymas',
    longDescription: 'tai yra funkcija, kuri leidžia automatizuoti namų apšvietimą ar kitus įrenginius pagal natūralų šviesos lygį, pasikeičiantį priklausomai nuo saulės pozicijos ir laiko. Ši funkcija remiasi geografinės padėties ir laiko duomenimis, kad būtų nustatyta, kada saulė leidžiasi ir kyla, ir pagal tai valdomi namų apšvietimo ar kiti parametrai.',
    shortDescription: '',
  },
  {
    name: 'Iki 100 laikmačių nustatymo kartai',
    group: 'valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 100 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Iki 250 laikmačių nustatymo kartai',
    group: 'valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 250 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Iki 256 laikmačių nustatymo kartai',
    group: 'valdymas',
    longDescription: 'Funkcija, kuri leidžia nustatyti iki 256 laikmačių nustatymo kartų.',
    shortDescription: '',
  },
  {
    name: 'Konfigūracijos galimybės, kurias nustato vartotojas',
    group: 'konfiguracija',
    longDescription: 'tai  yra svarbi funkcija, leidžianti vartotojams pritaikyti savo smart namų sistemą pagal individualius poreikius ir pageidavimus. Tai apima įvairias galimybes, kurias vartotojas gali nustatyti arba pasirinkti, siekiant optimizuoti savo namų automatizavimo sistemą.',
    shortDescription: '',
  },
  {
    name: 'Laikmačių programos',
    group: 'konfiguracija',
    longDescription: 'tai yra funkcija, kuri leidžia nustatyti įvairius veikimo laikus ar programus tam tikriems įrenginiams ar sistemoms, kai kalbama apie smart namų sistemas ar kitus automatizuotus sprendimus.',
    shortDescription: '',
  },
  {
    name: 'Įsijungimo šviesumą',
    group: 'konfiguracija',
    longDescription: 'tai yra parametras, nurodantis šviesos lygį arba intensyvumą, kai apšvietimo įrenginys arba sistema pirmą kartą įsijungia.',
    shortDescription: '',
  },
  {
    name: 'Mažiausią/maksimalų šviesumą',
    group: 'konfiguracija',
    longDescription: 'tai yra parametrai, nurodantys mažiausią ir didžiausią šviesos lygį arba intensyvumą, kurį apšvietimo įrenginys ar sistema gali pasiekti.',
    shortDescription: '',
  },
  {
    name: 'Įsijungimo/išsijungimo vėlavimus',
    group: 'konfiguracija',
    longDescription: 'tai yra parametrai, nustatantys laiko tarpą tarp komandos pateikimo įrenginiui įsijungti ar išsijungti ir paties įvykio įvykdymo.',
    shortDescription: '',
  },
  {
    name: 'Jutiklio judėjimo aptikimo zonas',
    group: 'konfiguracija',
    longDescription: 'tai yra sritis, kurioje judėjimo jutiklis stebi ir aptinka judėjimą.',
    shortDescription: '',
  },
  {
    name: 'Naktinio šviesos šaltinio funkciją',
    group: 'konfiguracija',
    longDescription: 'tai  yra funkcija, kuri leidžia įrenginiui arba sistemai veikti kaip šviesos šaltinis tamsoje, suteikiant silpną, bet pakankamą šviesą, kad būtų galima lengvai apsižvalgyti arba judėti naktį be didelio apšvietimo.',
    shortDescription: '',
  },
  {
    name: 'Viešbučio funkcija',
    group: 'konfiguracija',
    longDescription: 'tai  yra funkcija, kuri leidžia įrenginiui arba sistemai veikti kaip šviesos šaltinis tamsoje, suteikiant silpną, bet pakankamą šviesą, kad būtų galima lengvai apsižvalgyti arba judėti naktį be didelio apšvietimo.',
    shortDescription: '',
  },
  {
    name: 'Mėgstamiausi',
    group: 'konfiguracija',
    longDescription: 'tai funkcija, kuri leidžia vartotojui pažymėti arba išsaugoti mėgstamiausius daiktus, paslaugas ar funkcijas tam, kad jie būtų lengvai pasiekiami arba greitai pasiekiami vėliau.',
    shortDescription: '',
  },
  {
    name: 'Taisyklės',
    group: 'konfiguracija',
    longDescription: 'tai yra nustatytos instrukcijos ar procedūros, kurios nustato, kaip sistema turėtų elgtis ar veikti tam tikromis sąlygomis arba įvykių eigoje. Šios taisyklės gali būti naudojamos automatizuoti procesus, valdyti veiksmus arba priimti sprendimus remiantis įvairiais įvykiais ar duomenimis.',
    shortDescription: '',
  },
  {
    name: 'Balsinė paslauga',
    group: 'konfiguracija',
    longDescription: 'tai yra technologija arba funkcija, kuri leidžia vartotojams valdyti įrenginius arba gauti informaciją naudojant balsinius komandų įvesties metodus. Tai dažnai susiję su balsiniu asistentu, tokiu kaip „Amazon Alexa“, „Google Assistant“, „Apple Siri“ arba kitais, kurie geba atpažinti balsinius komandas ir vykdyti nurodymus pagal vartotojo norus.',
    shortDescription: '',
  },
  {
    name: 'Nuotolinis prieiga',
    group: 'konfiguracija',
    longDescription: '- tai yra funkcija arba galimybė valdyti arba pasiekti sistemą, įrenginį ar duomenis iš tolo, naudojant internetą arba kitas komunikacijos technologijas. Tai leidžia vartotojams valdyti savo įrenginius arba gauti informaciją, net jei jie nėra tiesiogiai prijungti prie tos sistemos lokaliai.',
    shortDescription: '',
  },
  {
    name: 'Tado° heating solution ',
    group: 'konfiguracija',
    longDescription: 'tai yra smart home sistema, skirta šildymo valdymui ir automatizavimui. Ši sistema leidžia vartotojams valdyti ir optimizuoti savo šildymo sistemą naudojant mobiliąją programėlę arba interneto naršyklę, kad būtų užtikrintas maksimalus komfortas ir energijos efektyvumas.',
    shortDescription: '',
  },
  {
    name: 'Philips Hue',
    group: 'konfiguracija',
    longDescription: 'tai yra viena iš populiariausių ir plačiausiai naudojamų smart home apšvietimo sistemų pasaulyje. Ši sistema leidžia vartotojams valdyti apšvietimą savo namuose naudojant mobiliąją programėlę arba balsines komandas, palaikantias tokias platformas kaip Amazon Alexa, Google Assistant ir Apple HomeKit.',
    shortDescription: '',
  },
  {
    name: 'Sonos',
    group: 'konfiguracija',
    longDescription: 'tai yra žinoma kompanija, kuri specializuojasi gamindama aukštos kokybės belaidžius garsiakalbius ir audio sistemos, skirtas namų garso sistemoms. Sonos garsiakalbiai yra žinomi dėl savo puikaus garso kokybės, lankstumo ir galimybių valdyti sistemą naudojant mobiliąją programėlę arba kitus įrenginius.',
    shortDescription: '',
  },
  {
    name: 'Vartotojo valdymas',
    group: 'vartotoju-valdymas',
    longDescription: 'tai yra procesas, kuriuo organizacija valdo savo vartotojų paskyras, teises, privilegijas ir prieigos lygius prie sistemos ar paslaugų. Tai apima vartotojų kūrimą, redagavimą, šalinimą ir bendro naudojimo teisių valdymą.',
    shortDescription: '',
  },
  {
    name: 'Vartotojas',
    group: 'vartotoju-valdymas',
    longDescription: 'Vartotojas su standartiniais leidimais.',
    shortDescription: '',
  },
  {
    name: 'Slaptažodis',
    group: 'vartotoju-valdymas',
    longDescription: 'Funkcija, leidžianti nustatyti slaptažodį vartotojo paskyrai.',
    shortDescription: '',
  },
  {
    name: 'Administratorius',
    group: 'vartotoju-valdymas',
    longDescription: 'Vartotojas su visais valdymo leidimais sistemoje.',
    shortDescription: '',
  },
  {
    name: 'Vartotojas su pakeičiamomis teisėmis ',
    group: 'vartotoju-valdymas',
    longDescription: 'tai yra vartotojas, kuriam suteiktos galios keisti arba redaguoti kitų vartotojų teises ir privilegijas sistemoje ar aplikacijoje.',
    shortDescription: '',
  },
  {
    name: 'Vartotojas be keitimo leidimų',
    group: 'vartotoju-valdymas',
    longDescription: 'Vartotojas, kuriam neleidžiama keisti nustatymų.',
    shortDescription: '',
  },
  {
    name: 'Administratorius su laisvai nustatomais leidimais',
    group: 'vartotoju-valdymas',
    longDescription: 'Administratorius su galimybe laisvai nustatyti vartotojų leidimus.',
    shortDescription: '',
  },
  {
    name: 'Iki 24 vartotojai su laisvai nustatomais leidimais',
    group: 'vartotoju-valdymas',
    longDescription: 'Sistema, leidžianti sukurti iki 24 vartotojus su laisvai nustatomais leidimais.',
    shortDescription: '',
  },
  {
    name: 'Administratorius su laisvai nustatomais leidimais',
    group: 'vartotoju-valdymas',
    longDescription: 'Administratorius su galimybe laisvai nustatyti vartotojų leidimus.',
    shortDescription: '',
  },
  {
    name: 'Iki 150 vartotojų su laisvai nustatomais leidimais',
    group: 'vartotoju-valdymas',
    longDescription: 'Sistema, leidžianti sukurti iki 150 vartotojų su laisvai nustatomais leidimais.',
    shortDescription: '',
  },
  {
    name: 'Buvimo simuliacija',
    group: 'saugumas',
    longDescription: 'Funkcija, kuri naudoja įrenginio atmintį ir laiko programavimą, norint sukurti buvimo simuliaciją. Galima sukurti simuliaciją, kuri tęsis 24 valandas, ir kuri naudos laiko programavimo funkciją. Taip pat galima sukurti specifiškai sukurtą simuliaciją, įtraukiant atsitiktinę funkciją.',
    shortDescription: '',
  },
  {
    name: 'Atsitiktinė buvimo simuliacija',
    group: 'saugumas',
    longDescription: 'Buvimo simuliacija, kurioje naudojamas atsitiktinės funkcijos elementas, kuris suteikia įspūdį, kad namuose yra žmonių, net kai jie nėra.',
    shortDescription: '',
  },
  {
    name: 'Logikos funkcijos (jeigu-tada)',
    group: 'logikos-funkcijos',
    longDescription: 'Ši funkcija leidžia nustatyti iki 32 jeigu-tada sąlygas su galimybe naudoti operatorius AND, OR ir XOR. Taip pat galima sukurti iki 250 jeigu-tada sąlygas su operatoriais AND, OR ir XOR. Šios funkcijos taip pat leidžia naudoti papildomas funkcijas, tokiu kaip skaitiklis, asmeniniai scenarijai ir neribojama jeigu-tada sąlygų kiekis.',
    shortDescription: '',
  },
  {
    name: 'Logikos funkcijos (jeigu-tada)',
    group: 'logikos-funkcijos',
    longDescription: 'Ši funkcija leidžia nustatyti iki 32 jeigu-tada sąlygas su galimybe naudoti operatorius AND, OR ir XOR. Taip pat galima sukurti iki 250 jeigu-tada sąlygas su operatoriais AND, OR ir XOR. Šios funkcijos taip pat leidžia naudoti papildomas funkcijas, tokiu kaip skaitiklis, asmeniniai scenarijai ir neribojama jeigu-tada sąlygų kiekis.',
    shortDescription: '',
  },
  {
    name: 'Automatinis apšvietimo valdymas',
    group: 'apsvietimas',
    value: 'automatinis-apsvietimo-valdymas',
    longDescription: 'Ši funkcija leidžia automatizuoti namų apšvietimą, taikant įvairius scenarijus ir valdymo būdus. Ji leidžia nustatyti apšvietimo lygį priklausomai nuo dienos laiko, judesio ar kitų parametrų. Tai ne tik padeda sutaupyti energiją, bet ir užtikrina patogumą ir saugumą.',
    shortDescription: '',
  },
  {
    name: 'Vartotojo buvimo sekimas',
    group: 'saugumas',
    value: 'vartotojo-buvimo-sekimas',
    longDescription: 'Vartotojo buvimo sekimas yra funkcija, kuri naudoja judesio jutiklius nustatyti, kada žmonės yra namuose arba išvykę. Tai leidžia stebėti ir valdyti namo saugumą bei efektyviai naudoti energiją, nustatant įspėjimus arba automatizuotus veiksmus priklausomai nuo vartotojų buvimo.',
    shortDescription: '',
  },
  {
    name: 'Klimato valdymas, inžinerinės sistemos',
    group: 'klimato-valdymas-inzinerines-sistemos',
    value: 'klimato-valdymas-inzinerines-sistemos',
    longDescription: 'Ši funkcija leidžia valdyti klimato parametrus namuose, įskaitant temperatūrą, drėgmę ir oro srautus. Ji taip pat integruojama su inžinerinėmis sistemomis, tokiomis kaip šildymas, vėdinimas ir oro kondicionavimas, siekiant užtikrinti optimalią aplinką vartotojams.',
    shortDescription: '',
  },
  {
    name: 'apsvietimas išmaniuosiuose namuose',
    group: 'apsvietimas-ismaniuosiuose-namuose',
    value: 'apsvietimas-ismaniuosiuose-namuose',
    longDescription: 'Ši funkcija leidžia valdyti apšvietimo sistemos veikimą išmaniuose namuose naudojant įvairias technologijas, tokias kaip LED šviesos šaltiniai ir išmanieji jungikliai. Tai ne tik suteikia vartotojams galimybę reguliuoti apšvietimo lygį ir atmosferą, bet ir padeda taupyti energiją.',
    shortDescription: '',
  },
  {
    name: 'Langų ir žaliuzių valdymas',
    group: 'langu-ir-zaliuziu-valdymas',
    value: 'langu-ir-zaliuziu-valdymas',
    longDescription: 'Ši funkcija leidžia valdyti langų ir žaliuzių veikimą išmaniuose namuose, naudojant automatizavimo technologijas. Tai apima galimybę atidaryti, uždaryti ar net reguliuoti langų atspalvį ir skaidrumą, taip pat valdyti žaliuzes priklausomai nuo dienos laiko ar išorės sąlygų.',
    shortDescription: '',
  },
  {
    name: 'Saugos sistemos',
    group: 'saugumas',
    value: 'saugumas',
    longDescription: 'Ši funkcija apima visus saugos sistemų komponentus ir funkcionalumus, skirtus apsaugoti namą ir gyventojus nuo įvairių pavojų, įskaitant vagystes, gaisrus ir nelaimingus atsitikimus. Tai apima judesio jutiklius, vaizdo stebėjimo kameras, dujų ir dūmų detektorius bei kitus saugos prietaisus.',
    shortDescription: '',
  },
  {
    name: 'Komforto įranga',
    group: 'komforto-iranga',
    value: 'komforto-iranga',
    longDescription: 'Ši funkcija apima įvairius įrangos sprendimus, kurie padeda padidinti vartotojų komfortą ir patogumą namuose. Tai gali būti susiję su ergonomiškomis baldų išdėstymo schemomis, specializuotomis patogumo funkcijomis ar net automatizuotomis kasdieninėmis veiklomis.',
   shortDescription: '',
  },
  {
    name: 'Energijos šaltiniai',
    group: 'energijos-saltiniai',
    value: 'energijos-saltiniai',
    longDescription: 'Ši funkcija apima skirtingus energijos tiekimo šaltinius, kurie gali būti naudojami namuose, įskaitant elektrą, dujas, saulės energiją ir kt. Tai leidžia vartotojams pasirinkti efektyviausią ir tvariausią energijos šaltinį, atsižvelgiant į jų poreikius ir aplinkosaugos aspektus.',
    shortDescription: '',
  },
  {
  name: 'Šutteriai',
  group: 'langu-ir-duru-valdymas',
  value: 'sutteriai',
  longDescription: 'Funkcija, skirta valdyti šutterius.',
  shortDescription: '',
  },

  {
  name: 'Ventiliacijos sklendės',
  group: 'langu-ir-duru-valdymas',
  value: 'ventiliacijos-sklendes',
  longDescription: 'Funkcija, skirta valdyti ventiliacijos sklendes.',
  shortDescription: '',
  },
  ];
module.exports = { functionalitiesToAdd };
